services:

  api:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.api
    entrypoint: ./dockerfiles/entrypoint.sh
    image: api_books:latest
    container_name: api
    ports:
      - "8000:8000"
    env_file: .env.api
    volumes:
      - ./data:/app/data

  dashboard:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dashboard
    image: dashboard_books:latest
    container_name: dashboard
    ports:
      - "8501:8501"
    env_file: .env.docker.dashboard
    depends_on:
      - api
