# fly.toml app configuration file generated for dashboard-books on 2025-07-17T23:50:35-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dashboard-books'
primary_region = 'gru'

[build]
  dockerfile = 'dockerfiles/Dockerfile.dashboard'

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
