# fly.toml app configuration file generated for api-books on 2025-07-16T20:52:30-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-books'
primary_region = 'gru'

[build]
  dockerfile = 'dockerfiles/Dockerfile.api'
  ignorefile = '.dockerignore'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  ALGORITHM="HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES=1

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
